version: '3.1'

services:
  core:
    build: .
    ports:
      - 8084:8084
    expose:
      - 8084
    container_name: core
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongo-compose-network
  mongo:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    container_name: mongo-core
    volumes:
      - /home/core/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge