version: '3.1'

services:
  core:
    build: .
    ports:
      - 8084:8084
    expose:
      - 8084
    container_name: core
    depends_on:
      - postgres-compose
    links:
      - postgres-compose
    networks:
      - postgres-compose-network
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - 15432:15432
    expose:
      - 15432
    container_name: postgres-core
    volumes:
      - /home/core/Docker/Volumes/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge